Mirror FTP directories to a GCS path in parallel
broadinstitute/long-read-pipelines pull request #179
Opened 2020-09-21 05:26 UTC by kvg

This workflow mirrors FTP directories to a specified GCS path, optionally placing the files in a directory based on the basename of the FTP directories.  The parallelism level of the mirroring operation is controllable with the 'num_simultaneous_downloads' setting so as not to accidentally DDOS the server.

2020-09-28 13:52 UTC, jonn-smith requested changes
A few questions and comments

2020-10-05 03:17 UTC, kvg commented on docker/lr-cloud-downloader/environment.yml
> +  - sra-tools
I've used the 'conda env export' functionality to make the environment very specific and stable.  We should adopt this as best practices for all of our Docker images.

2020-10-05 03:17 UTC, kvg commented on wdl/DownloadFromFTP.wdl
> +        for FTP_DIR in ~{sep=' ' ftp_dirs}
I've changed this now to read one line at a time from a temp file.

2020-10-05 03:18 UTC, kvg commented on wdl/DownloadFromFTP.wdl
> +            lftp -e 'find -l >> all_files.txt; exit' $FTP_DIR
I think for now, we can forego it; I haven't been downloading anything from servers that require authentication.  But in the future when this problem comes up, we'll of course have to make the necessary modifications.

2020-10-05 03:23 UTC, kvg commented on wdl/DownloadFromFTP.wdl
> +                echo "$gcsfile already exists."
Provided the files were uploaded by this tool, `gsutil cp` will automatically compute and compare md5 sums.

However, we do technically have an issue where the download from the FTP site might be corrupted, in which case, the upload to GCS will also be broken.  That's a problem I think worth thinking about in a future improvement to this tool.

2020-10-05 03:26 UTC, kvg commented on wdl/DownloadFromFTP.wdl
> +                RET=1
This was on purpose but admittedly lazy.  The logic was to let jobs that needed to download files automatically fail, and have the automatically retried job verify the files had been correctly downloaded and placed in GCS.  But that requires using up a retry for no good reason.  I've changed it to now check the return code of `lftp` and `gsutil cp`, and only set RET=1 if one of those tasks fails.  This should eliminate the need for a job to deliberately fail just so the uploads to GCS could be verified.

2020-10-05 03:27 UTC, kvg commented on wdl/DownloadFromFTP.wdl
> +    scatter (n in range(num_simultaneous_downloads)) {
Added comments now to clarify how this tool works.

2020-10-13 18:17 UTC, jonn-smith approved these changes
One quick comment about adding an issue into the repo.  The rest looks good.

2020-10-13 21:10 UTC, merged